### ISSUE TITLE
CI test error when merged the contribution guide PR

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/model-zoo#42]
Hi @yiheng-wang-nv ,

I received this error when I merged the contribution guide PR:
https://github.com/Project-MONAI/model-zoo/runs/7149069513?check_suite_focus=true
```
Successfully built gdown
Installing collected packages: numpy, typing-extensions, torch, filelock, tqdm, soupsieve, beautifulsoup4, gdown, monai, PySocks
Successfully installed PySocks-1.7.1 beautifulsoup4-4.11.1 filelock-3.7.1 gdown-4.5.1 monai-0.9.0 numpy-1.23.0 soupsieve-2.3.2.post1 torch-1.12.0 tqdm-4.64.0 typing-extensions-4.2.0
Downloading...
From: https://drive.google.com/uc?id=1IEMt3Y5fqLMtIe3TcdQvjNITVA0kb-lV
To: /tmp/tmpur8eqnq0/model.pt
  0%|          | 0.00/18.8M [00:00<?, ?B/s]
 25%|██▌       | 4.72M/18.8M [00:00<00:00, 37.1MB/s]
2022-07-01 11:26:[47](https://github.com/Project-MONAI/model-zoo/runs/7149069513?check_suite_focus=true#step:3:48),030 - INFO - Downloaded: /tmp/tmpjqir2bzt/brats_mri_segmentation/models/model.pt
2022-07-01 11:26:47,070 - INFO - Verified 'model.pt', md5: 870e677b782a5184cbc[48](https://github.com/Project-MONAI/model-zoo/runs/7149069513?check_suite_focus=true#step:3:49)db1456b78e8.
100%|██████████| 18.8M/18.8M [00:00<00:00, 102MB/s] 
Downloading...
From: https://drive.google.com/uc?id=1LLLnRJWq_Yl2CSMGu23Ls-joMd42mgnU
To: /tmp/tmp6ipir51a/model.ts
  0%|          | 0.00/18.9M [00:00<?, ?B/s]
 47%|████▋     | 8.91M/18.9M [00:00<00:00, 41.6MB/s]
2022-07-01 11:26:54,463 - INFO - Downloaded: /tmp/tmpjqir2bzt/brats_mri_segmentation/models/model.ts
2022-07-01 11:26:54,[50](https://github.com/Project-MONAI/model-zoo/runs/7149069513?check_suite_focus=true#step:3:51)2 - INFO - Verified 'model.ts', md5: c82f693c8f671e9899d21c2f241892f0.
100%|██████████| 18.9M/18.9M [00:00<00:00, 78.8MB/s]asset under the same name already exists: [brats_mri_segmentation_v0.1.0.zip]
Traceback (most recent call last):
  File "/home/runner/work/model-zoo/model-zoo/ci/update_model_info.py", line 133, in <module>
    main(changed_dirs)
  File "/home/runner/work/model-zoo/model-zoo/ci/update_model_info.py", line 120, in main
    raise AssertionError(f"update bundle: {bundle} failed. {msg}")
AssertionError: update bundle: brats_mri_segmentation failed. Upload bundle error: Command 'gh release upload hosting_storage_v1 /tmp/tmpjqir2bzt/brats_mri_segmentation_v0.1.0.zip -R Project-MONAI/model-zoo' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

Thanks.

**Comment by yiheng-wang-nv** [comment]
Thanks Nic. The root cause of the issue is that the program tries to upload bundles into the release, but there are already have bundles with same names inside it. The duplicate filenames are due to the version numbers of those changed bundles are not changed.

I will enhance the verification part of the version number  in our premerge ci tests to avoid this issue.
